# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliproducts', '0037_auto_20161218_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ('name', 'quantity', 'measure_unit'), 'verbose_name': 'presentación', 'verbose_name_plural': 'presentaciones'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ('name',), 'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
    ]
